steps:
    intro:
        key: intro
        root: yes
        instance: StepIntro
        setBackdrop:
            - desktop: '/site/coral.ru/assets/backdrop-intro-desktop.jpg'
              mobile: '/site/coral.ru/assets/backdrop-intro-mobile.jpg'
        choices:
            - label: "Поехали!"
              step: where-are-you-going-to
    where-are-you-going-to:
        key: where-are-you-going-to
        instance: StepSimpleChoice
        progress: true
        h2: "Начнем!"
        h3: "Вы уже знаете куда хотите отправиться?"
        setBackdrop: ''
        setSolidFill: '#FCDC61'
        choices:
            - label: 'Знаю'
              selected: true
              foreground:
                  - '/site/coral.ru/assets/backdrop-where2-know-desktop.png'
              step: know-where-timeframe
            - label: 'Не знаю'
              foreground:
                  - '/site/coral.ru/assets/backdrop-where2-dontknow-desktop.png'
              step: dont-know-where-budget
        behaviour:
            singleChoice: true
            selectOnHover: true
    know-where-timeframe:
        key: know-where-timeframe
        instance: StepSimpleChoice
        progress: true
        h3: "Тогда определимся с датой вылета"
        setBackdrop:
            - desktop: '/site/coral.ru/assets/backdrop-timeframe-desktop.jpg'
              mobile: '/site/coral.ru/assets/backdrop-timeframe-mobile.jpg'
        choices:
            - label: "Как можно скорее"
              actions:
                  - what: setPreferredTimeframe
                    predefined: asap
              step: know-where-budget
            - label: "Через 2 месяца"
              actions:
                  - what: setPreferredTimeframe
                    predefined: in2months
              step: know-where-budget
            - timeframePicker: true
              step: know-where-budget
        behaviour:
            resetSelection: resetPreferredTimeframe
            skip: know-where-budget
            singleChoice: true
    dont-know-where-timeframe:
        key: dont-know-where-timeframe
        instance: StepSimpleChoice
        progress: true
        h2: "Хорошо!"
        h3: "Теперь определимся с датой вылета"
        setBackdrop:
            - desktop: '/site/coral.ru/assets/backdrop-timeframe-desktop.jpg'
              mobile: '/site/coral.ru/assets/backdrop-timeframe-mobile.jpg'
        choices:
            - label: "Как можно скорее"
              actions:
                  - what: setPreferredTimeframe
                    predefined: asap
              step: dont-know-where-kind
            - label: "Через 2 месяца"
              actions:
                  - what: setPreferredTimeframe
                    predefined: in2months
              step: dont-know-where-kind
            - timeframePicker: true
              step: dont-know-where-kind
        behaviour:
            resetSelection: resetPreferredTimeframe
            skip: dont-know-where-kind
            singleChoice: true
    know-where-budget:
        key: know-where-budget
        instance: StepSimpleChoice
        progress: true
        h3: "Ваш комфортный бюджет на поездку"
        setBackdrop:
            - desktop: '/site/coral.ru/assets/backdrop-budget-desktop.jpg'
              mobile: '/site/coral.ru/assets/backdrop-budget-mobile.jpg'
        choices:
            - label:
                predefined: lowBudgetLabelMarkup
              step: destination-selector
              actions:
                  - what: setPreferredBudget
                    predefined: lowBudgetRange
            - label:
                predefined: mediumBudgetLabelMarkup
              step: destination-selector
              actions:
                  - what: setPreferredBudget
                    predefined: mediumBudgetRange
            - label:
                predefined: highBudgetLabelMarkup
              step: destination-selector
              actions:
                  - what: setPreferredBudget
                    predefined: highBudgetRange
        behaviour:
            resetSelection: resetPreferredBudget
            skip: destination-selector
            singleChoice: true
    dont-know-where-budget:
        key: dont-know-where-budget
        instance: StepSimpleChoice
        progress: true
        h2: "Хорошо!"
        h3: "Выберите рамки вашего бюджета"
        setBackdrop:
            - desktop: '/site/coral.ru/assets/backdrop-budget-desktop.jpg'
              mobile: '/site/coral.ru/assets/backdrop-budget-mobile.jpg'
        choices:
            - label:
                predefined: lowBudgetLabelMarkup
              actions:
                  - what: setPreferredBudget
                    predefined: lowBudgetRange
              step: dont-know-where-flight
            - label:
                predefined: mediumBudgetLabelMarkup
              actions:
                  - what: setPreferredBudget
                    predefined: mediumBudgetRange
              step: dont-know-where-flight
            - label:
                predefined: highBudgetLabelMarkup
              actions:
                  - what: setPreferredBudget
                    predefined: highBudgetRange
              step: dont-know-where-flight
        behaviour:
            resetSelection: resetPreferredBudget
            skip: dont-know-where-flight
            singleChoice: true
    dont-know-where-flight:
        key: dont-know-where-flight
        instance: StepSimpleChoice
        progress: true
        h2: "Отлично!"
        h3: "Выберите приемлемое для вас время перелета"
        setBackdrop:
            - desktop: '/site/coral.ru/assets/backdrop-flight-desktop.jpg'
              mobile: '/site/coral.ru/assets/backdrop-flight-mobile.jpg'
              h2MobileColor: 'white'
        setSolidFill: 'transparent'
        choices:
            - label: "до 6 часов"
              actions:
                  - what: setMaxFlightDuration
                    predefined: 6
              step: dont-know-where-timeframe
            - label: "до 12 часов"
              actions:
                  - what: setMaxFlightDuration
                    predefined: 12
              step: dont-know-where-timeframe
            - label: "неважно"
              actions:
                  - what: setMaxFlightDuration
                    predefined: 1000000
              step: dont-know-where-timeframe
        behaviour:
            resetSelection: resetMaxFlightDuration
            skip: dont-know-where-timeframe
            singleChoice: true
    dont-know-where-kind:
        key: dont-know-where-kind
        instance: StepMultipleChoice
        progress: true
        h2: 'Замечательно!'
        h3: 'А какой тип отдыха вам интересен?'
        hint: 'можно выбрать несколько вариантов'
        setBackdrop:
            - key: beach
              h2MobileColor: '#033870'
              desktop: '/site/coral.ru/assets/backdrop-kind-beach-desktop.jpg'
              mobile: '/site/coral.ru/assets/backdrop-kind-beach-mobile.jpg'
        behaviour:
            toggle: true
            skip: dont-know-where-destination-selector
            step: dont-know-where-destination-selector
            proceedWithActions:
                - setPreferredLeisureKindsFromCurrentStep
                - preserveBackdropFromCurrentStep
        choices: []

    dont-know-where-destination-selector:
        key: dont-know-where-destination-selector
        instance: DestinationSelector
        progress: true
        h3: 'Выберите куда вы хотите полететь'
        setBackdrop: ''
        setSolidFill: 'transparent'
        choices: []
        behaviour:
            singleChoice:  true
            selectOnHover: true
