steps:
    intro:
        root: yes
        instance: StepIntro
        setBackdrop:
            - desktop: '/site/coral.ru/assets/backdrop-intro-desktop.jpg'
              mobile: '/site/coral.ru/assets/backdrop-intro-mobile.jpg'
        choices:
            - label: "Поехали!"
              step: where-are-you-going-to
    where-are-you-going-to:
        instance: StepSimpleChoice
        progress: show
        h2: "Начнем!"
        h3: "Вы уже знаете куда хотите отправиться?"
        setBackdrop: ''
        setSolidFill: '#FCDC61'
        choices:
            - label: Знаю
              step:
            - label: Не знаю
              step:
