steps:
    intro:
        key: intro
        root: yes
        instance: StepIntro
        setBackdrop:
            - desktop: '/site/coral.ru/assets/backdrop-intro-desktop.jpg'
              mobile: '/site/coral.ru/assets/backdrop-intro-mobile.jpg'
        choices:
            - label: "Поехали!"
              step: where-are-you-going-to
    where-are-you-going-to:
        key: where-are-you-going-to
        instance: StepSimpleChoice
        progress: true
        h2: "Начнем!"
        h3: "Вы уже знаете куда хотите отправиться?"
        setBackdrop: ''
        setSolidFill: '#FCDC61'
        choices:
            - label: 'Знаю'
              selected: true
              foreground:
                  - '/site/coral.ru/assets/backdrop-where2-know-desktop.png'
              step: know-where-timeframe
            - label: 'Не знаю'
              foreground:
                  - '/site/coral.ru/assets/backdrop-where2-dontknow-desktop.png'
              step:
        behaviour:
            singleChoice: true
            selectOnHover: true
    know-where-timeframe:
        key: know-where-timeframe
        instance: StepSimpleChoice
        progress: true
        h3: "Тогда определимся с датой вылета"
        setBackdrop:
            - desktop: '/site/coral.ru/assets/backdrop-timeframe-desktop.jpg'
              mobile: '/site/coral.ru/assets/backdrop-timeframe-mobile.jpg'
        choices:
            - label: "Как можно скорее"
              actions:
                  - what: setPreferredTimeframe
                    predefined: asap
              step: know-where-budget
            - label: "Через 2 месяца"
              actions:
                  - what: setPreferredTimeframe
                    predefined: in2months
              step: know-where-budget
            - timeframePicker: true
              step: know-where-budget
        behaviour:
            resetSelection: true
            skippable: true
            singleChoice: true
    know-where-budget:
        key: know-where-budget
        instance: StepSimpleChoice
        progress: true
        h3: "Ваш комфортный бюджет на поездку"
        setBackdrop:
            - desktop: '/site/coral.ru/assets/backdrop-budget-desktop.jpg'
              mobile: '/site/coral.ru/assets/backdrop-budget-mobile.jpg'
        choices:
            - label:
                predefined: lowBudgetLabel
            - label:
                predefined: mediumBudgetLabel
            - label:
                predefined: highBudgetLabel
        behaviour:
            resetSelection: true
            skippable: true
            singleChoice: true

