steps:
    intro:
        key: intro
        root: yes
        instance: StepIntro
        setBackdrop:
            - desktop: '/site/coral.ru/assets/backdrop-intro-desktop.jpg'
              mobile: '/site/coral.ru/assets/backdrop-intro-mobile.jpg'
        choices:
            - label: "Поехали!"
              step: where-are-you-going-to
    where-are-you-going-to:
        key: where-are-you-going-to
        instance: StepSimpleChoice
        progress: true
        h2: "Начнем!"
        h3: "Вы уже знаете куда хотите отправиться?"
        setBackdrop: ''
        setSolidFill: '#FCDC61'
        choices:
            - label: 'Знаю'
              selected: true
              foreground:
                  - '/site/coral.ru/assets/backdrop-where2-know-desktop.png'
              step: know-where-timeframe
            - label: 'Не знаю'
              foreground:
                  - '/site/coral.ru/assets/backdrop-where2-dontknow-desktop.png'
              step: dont-know-where-budget
        behaviour:
            singleChoice: true
            selectOnHover: true
            proceedWithActions: resetPreferredSearchParams
    know-where-timeframe:
        key: know-where-timeframe
        instance: StepSimpleChoice
        progress: true
        h3: "Тогда определимся с датой вылета"
        setBackdrop:
            - desktop: '/site/coral.ru/assets/backdrop-timeframe-desktop.jpg'
              mobile: '/site/coral.ru/assets/backdrop-timeframe-mobile.jpg'
        choices:
            - label: "Как можно скорее"
              actions:
                  - what: setPreferredTimeframe
                    predefined: asap
              step: know-where-budget
            - label: "Через 2 месяца"
              actions:
                  - what: setPreferredTimeframe
                    predefined: in2months
              step: know-where-budget
            - timeframePicker: true
              step: know-where-budget
        behaviour:
            resetSelection: resetPreferredTimeframe
            skip: know-where-budget
            singleChoice: true
    dont-know-where-timeframe:
        key: dont-know-where-timeframe
        instance: StepSimpleChoice
        progress: true
        h2: "Хорошо!"
        h3: "Теперь определимся с датой вылета"
        setBackdrop:
            - desktop: '/site/coral.ru/assets/backdrop-timeframe-desktop.jpg'
              mobile: '/site/coral.ru/assets/backdrop-timeframe-mobile.jpg'
        choices:
            - label: "Как можно скорее"
              actions:
                  - what: setPreferredTimeframe
                    predefined: asap
              step: dont-know-where-kind
            - label: "Через 2 месяца"
              actions:
                  - what: setPreferredTimeframe
                    predefined: in2months
              step: dont-know-where-kind
            - timeframePicker: true
              step: dont-know-where-kind
        behaviour:
            resetSelection: resetPreferredTimeframe
            skip: dont-know-where-kind
            singleChoice: true
    know-where-budget:
        key: know-where-budget
        instance: StepSimpleChoice
        progress: true
        h3: "Ваш комфортный бюджет на поездку"
        setBackdrop:
            - desktop: '/site/coral.ru/assets/backdrop-budget-desktop.jpg'
              mobile: '/site/coral.ru/assets/backdrop-budget-mobile.jpg'
        choices:
            - label:
                predefined: lowBudgetLabelMarkup
              step: know-where-destination-selector
              actions:
                  - what: setPreferredBudget
                    predefined: lowBudgetRange
            - label:
                predefined: mediumBudgetLabelMarkup
              step: know-where-destination-selector
              actions:
                  - what: setPreferredBudget
                    predefined: mediumBudgetRange
            - label:
                predefined: highBudgetLabelMarkup
              step: know-where-destination-selector
              actions:
                  - what: setPreferredBudget
                    predefined: highBudgetRange
        behaviour:
            resetSelection: resetPreferredBudget
            skip: know-where-destination-selector
            step: know-where-destination-selector
            singleChoice: true
    dont-know-where-budget:
        key: dont-know-where-budget
        instance: StepSimpleChoice
        progress: true
        h2: "Хорошо!"
        h3: "Выберите рамки вашего бюджета"
        setBackdrop:
            - desktop: '/site/coral.ru/assets/backdrop-budget-desktop.jpg'
              mobile: '/site/coral.ru/assets/backdrop-budget-mobile.jpg'
        choices:
            - label:
                predefined: lowBudgetLabelMarkup
              actions:
                  - what: setPreferredBudget
                    predefined: lowBudgetRange
              step: dont-know-where-flight
            - label:
                predefined: mediumBudgetLabelMarkup
              actions:
                  - what: setPreferredBudget
                    predefined: mediumBudgetRange
              step: dont-know-where-flight
            - label:
                predefined: highBudgetLabelMarkup
              actions:
                  - what: setPreferredBudget
                    predefined: highBudgetRange
              step: dont-know-where-flight
        behaviour:
            resetSelection: resetPreferredBudget
            skip: dont-know-where-flight
            singleChoice: true
    dont-know-where-flight:
        key: dont-know-where-flight
        instance: StepSimpleChoice
        progress: true
        h2: "Отлично!"
        h3: "Выберите приемлемое для вас время перелета"
        setBackdrop:
            - desktop: '/site/coral.ru/assets/backdrop-flight-desktop.jpg'
              mobile: '/site/coral.ru/assets/backdrop-flight-mobile.jpg'
              h2MobileColor: 'white'
        setSolidFill: 'transparent'
        choices:
            - label: "до 6 часов"
              actions:
                  - what: setMaxFlightDuration
                    predefined: 6
              step: dont-know-where-timeframe
            - label: "до 12 часов"
              actions:
                  - what: setMaxFlightDuration
                    predefined: 12
              step: dont-know-where-timeframe
            - label: "неважно"
              actions:
                  - what: setMaxFlightDuration
                    predefined: 1000000
              step: dont-know-where-timeframe
        behaviour:
            resetSelection: resetMaxFlightDuration
            skip: dont-know-where-timeframe
            singleChoice: true
    dont-know-where-kind:
        key: dont-know-where-kind
        instance: StepMultipleChoice
        progress: true
        h2: 'Замечательно!'
        h3: 'А какой тип отдыха вам интересен?'
        hint: 'можно выбрать несколько вариантов'
        setBackdrop:
            - key: beach
              h2MobileColor: '#033870'
              desktop: '/site/coral.ru/assets/backdrop-kind-beach-desktop.jpg'
              mobile: '/site/coral.ru/assets/backdrop-kind-beach-mobile.jpg'
        behaviour:
            toggle: true
            skip: dont-know-where-destination-selector
            step: dont-know-where-destination-selector
            proceedWithActions:
                - setPreferredLeisureKindsFromCurrentStep
                - preserveBackdropFromCurrentStep
        choices: []

    know-where-destination-selector:
        key: know-where-destination-selector
        instance: DestinationSelector
        progress: true
        h3: 'Выберите куда вы хотите полететь'
        setBackdrop: ''
        setSolidFill: 'transparent'
        choices: []
        behaviour:
            singleChoice:  true
            selectOnHover: false

    dont-know-where-destination-selector:
        key: dont-know-where-destination-selector
        instance: DestinationSelector
        progress: true
        h3: 'Выберите куда вы хотите полететь'
        setBackdrop: ''
        setSolidFill: 'transparent'
        choices: []
        behaviour:
            singleChoice:  true
            selectOnHover: false

    regions-turkey:
        key: regions-turkey
        instance: StepSimpleChoice
        progress: true
        h2: 'Tamam, tamam!'
        h3: 'Что для вас более заманчиво?'
        setBackdrop:
            - desktop: '/site/coral.ru/assets/backdrop-destination-turkey-azure-desktop.jpg'
              mobile: '/site/coral.ru/assets/backdrop-destination-turkey-azure-mobile.jpg'
              h2MobileColor: 'white'
        setSolidFill: 'transparent'
        choices:
            - label: 'Горы и лазурные бухты'
              selected: true
              step: must-have
              actions:
                  - what: setBackdrop
                    predefined:
                        desktop: '/site/coral.ru/assets/backdrop-destination-turkey-azure-desktop.jpg'
                        mobile: '/site/coral.ru/assets/backdrop-destination-turkey-azure-mobile.jpg'
                        h2MobileColor: 'white'
                  - what: setRegionFilter
                    predefined: [29, 31, 17, 18, 210, 209, 30, 19, 10732, 20, 21, 22, 32, 23, 24, 25, 28, 27, 8654, 8653, 40, 46, 8995, 9113, 8657, 8655, 51, 8425, 52, 9114, 55, 57, 11080, 130, 59, 60, 58, 14551, 61, 8239, 1931, 45, 43, 44, 41, 2130, 8992, 37]
            - label: 'Солнце, пляж и море'
              step: must-have
              actions:
                  - what: setBackdrop
                    predefined:
                        desktop: '/site/coral.ru/assets/backdrop-destination-turkey-beach-desktop.jpg'
                        mobile: '/site/coral.ru/assets/backdrop-destination-turkey-beach-mobile.jpg'
                        h2MobileColor: 'white'
                  - what: setRegionFilter
                    predefined: [4, 3, 6, 8, 9, 67, 69, 70, 72, 10646, 2131, 79, 84, 87, 90, 91, 1948, 98, 100, 102, 1949, 1950, 1952, 1951, 10645, 50, 49, 107, 111, 106, 113, 114, 109, 10644, 120, 121, 122, 123, 119, 124, 125, 10647, 127, 128]
            - label: 'Мечети, базары, местный колорит'
              step: must-have
              actions:
                  - what: setBackdrop
                    predefined:
                        desktop: '/site/coral.ru/assets/backdrop-destination-turkey-bazaar-desktop.jpg'
                        mobile: '/site/coral.ru/assets/backdrop-destination-turkey-bazaar-mobile.jpg'
                        h2MobileColor: 'white'
                  - what: setRegionFilter
                    predefined: [79, 84, 87, 90, 91, 10987, 11008, 145, 11007, 8895, 150, 8900, 10988, 8903, 149, 141, 8905, 151, 8885, 206, 148, 137, 8894, 8891, 8883, 8892, 11016, 11010, 8882, 11009, 8878, 11013, 204, 8889, 8877, 10997, 146, 8902, 8887, 11011, 11015, 8901, 153, 8888, 11017, 8893, 8974, 9128, 205, 147, 139, 143, 11014, 142, 152, 8899, 11001, 8898, 11002, 8890, 8896, 155, 156, 140, 144, 8904, 8884, 9004, 10993]
        behaviour:
            singleChoice:  true
            selectOnHover: true
            proceedWithActions: preserveBackdropFromCurrentStep
            resetOnStepback: resetRegionFilter

    regions-egypt:
        key: regions-egypt
        instance: StepSimpleChoice
        progress: true
        h2: 'Шукран!'
        h3: 'Что для вас более заманчиво?'
        setBackdrop:
            - desktop: '/site/coral.ru/assets/backdrop-destination-egypt-hurghada-desktop.jpg'
              mobile: '/site/coral.ru/assets/backdrop-destination-egypt-hurghada-mobile.jpg'
              h2MobileColor: 'white'
        setSolidFill: 'transparent'
        choices:
            - label: 'Солнце, пляж и морской бриз'
              selected: true
              step: must-have
              actions:
                  - what: setBackdrop
                    predefined:
                        desktop: '/site/coral.ru/assets/backdrop-destination-egypt-hurghada-desktop.jpg'
                        mobile: '/site/coral.ru/assets/backdrop-destination-egypt-hurghada-mobile.jpg'
                        h2MobileColor: 'white'
                  - what: setRegionFilter
                    predefined: [1969, 1967, 1966, 14453, 171, 174, 175, 176, 169, 173, 1968]
            - label: 'Кораллы, ласты, акваланг'
              step: must-have
              actions:
                  - what: setBackdrop
                    predefined:
                        desktop: '/site/coral.ru/assets/backdrop-destination-egypt-sharm-desktop.jpg'
                        mobile: '/site/coral.ru/assets/backdrop-destination-egypt-sharm-mobile.jpg'
                        h2MobileColor: 'white'
                  - what: setRegionFilter
                    predefined: [184, 183, 1771, 186, 194, 1770]
        behaviour:
            singleChoice:  true
            selectOnHover: true
            proceedWithActions: preserveBackdropFromCurrentStep
            resetOnStepback: resetRegionFilter

    regions-uae:
        key: regions-uae
        instance: StepSimpleChoice
        progress: true
        h2: 'Шукран!'
        h3: 'Что для вас более заманчиво?'
        setBackdrop:
            - desktop: '/site/coral.ru/assets/backdrop-destination-uae-fun-desktop.jpg'
              mobile: '/site/coral.ru/assets/backdrop-destination-uae-fun-mobile.jpg'
              h2MobileColor: 'white'
        setSolidFill: 'transparent'
        choices:
            - label: 'Веселье, распродажи, небоскрёбы'
              selected: true
              step: must-have
              actions:
                  - what: setBackdrop
                    predefined:
                        desktop: '/site/coral.ru/assets/backdrop-destination-uae-fun-desktop.jpg'
                        mobile: '/site/coral.ru/assets/backdrop-destination-uae-fun-mobile.jpg'
                        h2MobileColor: 'white'
                  - what: setRegionFilter
                    predefined: [322, 10662, 11507, 8933, 10985, 10983, 841, 11331, 11346, 10717, 842, 218, 11342, 845, 10982, 11347, 11356, 843]
            - label: 'Море, пляжи и релакс'
              step: must-have
              actions:
                  - what: setBackdrop
                    predefined:
                        desktop: '/site/coral.ru/assets/backdrop-destination-uae-beach-desktop.jpg'
                        mobile: '/site/coral.ru/assets/backdrop-destination-uae-beach-mobile.jpg'
                        h2MobileColor: 'white'
                  - what: setRegionFilter
                    predefined: [360, 327]
        behaviour:
            singleChoice:  true
            selectOnHover: true
            proceedWithActions: preserveBackdropFromCurrentStep
            resetOnStepback: resetRegionFilter

    regions-russia:
        key: regions-russia
        instance: StepSimpleChoice
        progress: true
        h3: 'Что для вас более заманчиво?'
        setBackdrop:
            - desktop: '/site/coral.ru/assets/backdrop-destination-russia-beach-desktop.jpg'
              mobile: '/site/coral.ru/assets/backdrop-destination-russia-beach-mobile.jpg'
              h2MobileColor: 'white'
        setSolidFill: 'transparent'
        choices:
            - label: 'Море, пляж и солнце'
              selected: true
              step: must-have
              actions:
                  - what: setBackdrop
                    predefined:
                        desktop: '/site/coral.ru/assets/backdrop-destination-russia-beach-desktop.jpg'
                        mobile: '/site/coral.ru/assets/backdrop-destination-russia-beach-mobile.jpg'
                        h2MobileColor: 'white'
                  - what: setRegionFilter
                    predefined: [5417, 9195, 9198, 9193, 9509, 9181, 11077, 9199, 9194, 10783, 10776, 9197, 11275, 1545, 9184, 9183, 9196, 9186, 9187, 9188, 1595, 9192]
            - label: 'Нарзан, горы, оздоровление'
              step: must-have
              actions:
                  - what: setBackdrop
                    predefined:
                        desktop: '/site/coral.ru/assets/backdrop-destination-russia-narzan-desktop.jpg'
                        mobile: '/site/coral.ru/assets/backdrop-destination-russia-narzan-mobile.jpg'
                        h2MobileColor: 'white'
                  - what: setRegionFilter
                    predefined: [1135, 8355, 1220, 1334, 1465, 9684]
            - label: 'Лыжи и горные вершины'
              step: must-have
              actions:
                  - what: setBackdrop
                    predefined:
                        desktop: '/site/coral.ru/assets/backdrop-destination-russia-ski-desktop.jpg'
                        mobile: '/site/coral.ru/assets/backdrop-destination-russia-ski-mobile.jpg'
                        h2MobileColor: 'white'
                  - what: setRegionFilter
                    predefined: [9826, 9820, 9819, 9822, 9823, 9181, 9811]
        behaviour:
            singleChoice:  true
            selectOnHover: true
            proceedWithActions: preserveBackdropFromCurrentStep
            resetOnStepback: resetRegionFilter

    must-have:
        key: must-have
        instance: StepSimpleChoice
        layout: two-columns
        progress: true
        h2: 'Уточним детали!'
        h3: 'Выберите что для вас наиболее важно на отдыхе'
        setBackdrop:
            - desktop: '/site/coral.ru/assets/backdrop-musthave-filter-desktop.jpg'
              mobile: '/site/coral.ru/assets/backdrop-musthave-filter-mobile.jpg'
              h2MobileColor: 'white'
        setSolidFill: 'transparent'
        choices:
            - label: 'Крытый бассейн'
              step: fin
              actions:
                  - what: setMusthaveFilter
                    predefined: { Hf: [4] }
            - label: 'Песчаный пляж'
              step: fin
              actions:
                  - what: setMusthaveFilter
                    predefined: { Bch: [13] }
            - label: 'VIP-отели, Элитный отдых'
              step: fin
              actions:
                  - what: setMusthaveFilter
                    predefined: { Lt: [1,49] }
            - label: 'Аквапарк и водные горки'
              step: fin
              actions:
                  - what: setMusthaveFilter
                    predefined: { Hf: [8] }
            - label: 'Отель только для взрослых'
              step: fin
              actions:
                  - what: setMusthaveFilter
                    predefined: { Lt: [25] }
            - label: 'Балкон или терраса'
              step: fin
              actions:
                  - what: setMusthaveFilter
                    predefined: { Rf: [14] }
            - label: 'Дискотека'
              step: fin
              actions:
                  - what: setMusthaveFilter
                    predefined: { Hf: [3] }
        behaviour:
            singleChoice:  true
            resetSelection: resetMusthaveFilter
            skip: fin
            step: fin

    fin:
        key: fin
        instance: StepFinal
        progress: true
        h2: 'Cупер! Последний шаг'
        setBackdrop:
            - desktop: '/site/coral.ru/assets/backdrop-final-desktop.jpg'
              mobile: '/site/coral.ru/assets/backdrop-final-mobile.jpg'
              h2MobileColor: 'white'
        setSolidFill: 'transparent'
        choices: []

