steps:
    intro:
        key: intro
        root: yes
        instance: StepIntro
        setBackdrop:
            - desktop: '/site/coral.ru/assets/backdrop-intro-desktop.jpg'
              mobile: '/site/coral.ru/assets/backdrop-intro-mobile.jpg'
        choices:
            - label: "Поехали!"
              step: where-are-you-going-to
    where-are-you-going-to:
        key: where-are-you-going-to
        instance: StepSimpleChoice
        progress: show
        h2: "Начнем!"
        h3: "Вы уже знаете куда хотите отправиться?"
        setBackdrop: ''
        setSolidFill: '#FCDC61'
        choices:
            - label: 'Знаю'
              selected: true
              foreground:
                  - '/site/coral.ru/assets/backdrop-where2-know-desktop.png'
              step: know-where-timeframe
            - label: 'Не знаю'
              foreground:
                  - '/site/coral.ru/assets/backdrop-where2-dontknow-desktop.png'
              step:
        behaviour:
            singleChoice: true
            selectOnHover: true
    know-where-timeframe:
        key: know-where-timeframe
        instance: StepSimpleChoice
        progress: show
        h3: "Тогда определимся с датой вылета"
        setBackdrop:
            - desktop: '/site/coral.ru/assets/backdrop-timeframe-desktop.jpg'
              mobile: '/site/coral.ru/assets/backdrop-timeframe-mobile.jpg'
        choices:
            - label: "Как можно скорее"
            - label: "Через 2 месяца"
            - timeframePicker: true
        behaviour:
            skippable: true
            singleChoice: true
