- id: turkey
  name: "Турция"
  flightDuration: 4
- id: egypt
  name: "Египет"
  flightDuration: 5
- id: uae
  name: "ОАЭ"
  flightDuration: 5
- id: bahrain
  name: "Бахрейн"
  flightDuration: 5
- id: thailand
  name: "Таиланд"
  flightDuration: 9
- id: maldives
  name: "Мальдивы"
  flightDuration: 15
- id: cuba
  name: "Куба"
  flightDuration: 13
- id: russia
  name: "Россия"
  flightDuration: 6
- id: az
  name: "Азербайджан"
  flightDuration: 3
- id: uz
  name: "Узбекистан"
  flightDuration: 4
- id: belarus
  name: "Беларусь"
  flightDuration: 3
- id: armenia
  name: "Армения"
  flightDuration: 4
